### ISSUE TITLE
Error: wrong return type

### ISSUE THREAD

**Issue by frasza** [Chevifier/QuestManager#16]
Hello,

Recently I have started learning game dev and Godot, so I wanted to check out the addon but I am facing issue.
I am running Godot 4.2.2 and addon version 0.8.2, and whenever I try to test quests, even ones in Examples, I get error:

`Trying to return an array of type "Array" where expected return type is "Array[Dictionary]".`

![image](https://github.com/Chevifier/QuestManager/assets/22049682/3a370862-0195-40bf-a57c-5854e9c48f98)

**Comment by Chevifier** [comment]
Sorry for the late update, Ive fixed this issue. I had code I was testing that I didn't remove from the main release. Its now fixed with update 0.8.3. The last 3 lines of add quest were for testing quests as class objects instead of dictionaries. Didn't get around to fully implementing it yet. But it will allow tracking quests to be easier using signals directly in each "Quest object step".
